-- CREACION DE BD
DROP DATABASE IF EXISTS MERUSSI ;
CREATE DATABASE MERUSSI ;
USE MERUSSI;

-- CREACION DE TABLAS

CREATE TABLE ROL (
	ID_ROL INT NOT NULL auto_increment,
    DESCRIPCION VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_ROL)
);

CREATE TABLE TIPO_DOCUMENTO (
	ID_TIPODOC INT NOT NULL auto_increment,
    DESCRIPCION VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_TIPODOC)
);

CREATE TABLE POSTAL (
	ID_POSTAL INT  NOT NULL auto_increment,
    LOCALIDAD VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_POSTAL)
);

CREATE TABLE PROVINCIA (
	ID_PROVINCIA INT NOT NULL auto_increment,
    DESCRIPCION VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_PROVINCIA)
);

CREATE TABLE FORMA_DE_PAGO (
	ID_FPAGO INT NOT NULL auto_increment,
    DESCRIPCION VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_FPAGO)
);

CREATE TABLE CATEGORIA (
	ID_CATEGORIA INT NOT NULL auto_increment,
    DESCRIPCION VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_CATEGORIA)
);


CREATE TABLE PERSONA (
	ID_PERSONA INT NOT NULL auto_increment,
    ID_ROL INT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    ID_TIPODOC INT NOT NULL,
    NRO_DOCUMENTO VARCHAR(20) NOT NULL,
    FEC_NACIMIENTO DATE DEFAULT (current_date()),
    DIRECCION_NRO NUMERIC(4,0)  NOT NULL,
    DIRECCION_CALLE VARCHAR(30) NOT NULL,
    ID_POSTAL INT NOT NULL,
    ID_PROVINCIA INT NOT NULL,
    PRIMARY KEY (ID_PERSONA)	
);


CREATE TABLE PRODUCTO (
	ID_PRODUCTO INT NOT NULL auto_increment,
    ID_CATEGORIA INT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    FEC_VENCIMIENTO DATE NOT NULL,
    PRECIO NUMERIC(18,2),
    PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PRODUCTO_STOCK (
	ID_STOCK INT NOT NULL auto_increment,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD NUMERIC(5,0) NOT NULL,
    PRIMARY KEY (ID_STOCK)
);

CREATE TABLE FACTURA (
	ID_FACTURA INT NOT NULL auto_increment,
    COD_EMPLEADO INT NOT NULL,
    COD_CLIENTE INT NOT NULL,
    FEC_EMISION DATE NOT NULL DEFAULT (current_date()),
    OBERVACIONES VARCHAR(100) DEFAULT "SIN OBSERVACIONES",
    PRIMARY KEY (ID_FACTURA)
);


CREATE TABLE FACTURA_DETALLE (
    ID_DETALLE INT NOT NULL AUTO_INCREMENT,
    ID_FACTURA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD NUMERIC(3,0) NOT NULL,
    TOTAL NUMERIC(18,2),
    PRIMARY KEY (ID_DETALLE),
    UNIQUE KEY (ID_FACTURA, ID_PRODUCTO, ID_DETALLE)
);

CREATE TABLE FACTURA_PAGO (
    ID_PAGO INT NOT NULL AUTO_INCREMENT,
    ID_FACTURA INT NOT NULL,
    ID_FPAGO INT NOT NULL,
	TOTAL NUMERIC(18,2) NOT NULL,
    PRIMARY KEY (ID_PAGO),
    UNIQUE KEY (ID_PAGO, ID_FACTURA, ID_FPAGO)
);