-- AGREGO LAS RELACIONES CON LAS TABLAS.

-- foreign keys

-- PRODUCTO CON RELACION A CATEGORIA
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY FK_PRODUCTO_CATEGORIA (ID_CATEGORIA) 
	REFERENCES CATEGORIA (ID_CATEGORIA);

-- PERSONA CON RELACION A ROL
ALTER TABLE PERSONA ADD CONSTRAINT FK_ROL_PERSONA FOREIGN KEY FK_ROL_PERSONA (ID_ROL) 
	REFERENCES rol (ID_ROL);

-- PERSONA CON RELACION A TIPO_DOCUMENTO
ALTER TABLE PERSONA ADD CONSTRAINT FK_TIPODOC_PERSONA FOREIGN KEY FK_TIPODOC_PERSONA (ID_TIPODOC)
    REFERENCES TIPO_DOCUMENTO (ID_TIPODOC);

-- PERSONA CON RELACION A POSTAL
ALTER TABLE PERSONA ADD CONSTRAINT FK_POSTAL_PERSONA FOREIGN KEY FK_POSTAL_PERSONA (ID_POSTAL)
    REFERENCES POSTAL (ID_POSTAL);

-- PERSONA CON RELACION A PROVINCIA
ALTER TABLE PERSONA ADD CONSTRAINT FK_PROVINCIA_PERSONA FOREIGN KEY FK_PROVINCIA_PERSONA (ID_PROVINCIA)
    REFERENCES PROVINCIA (ID_PROVINCIA);

-- PRODUCTO_STOCK CON RELACION A PRODUCTO
ALTER TABLE PRODUCTO_STOCK ADD CONSTRAINT FK_PRODUCTO_PRODUCTO_STOCK FOREIGN KEY FK_PRODUCTO_PRODUCTO_STOCK (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID_PRODUCTO);

-- FACTURA CON RELACION A PERSONA PARA ROL EMPLEADO Y CLIENTE
ALTER TABLE FACTURA ADD CONSTRAINT FK_EMPLEADO_FACTURA FOREIGN KEY FK_EMPLEADO_FACTURA (COD_EMPLEADO)
    REFERENCES PERSONA (ID_PERSONA);

ALTER TABLE FACTURA ADD CONSTRAINT FK_CLIENTE_FACTURA FOREIGN KEY FK_CLIENTE_FACTURA (COD_CLIENTE)
    REFERENCES PERSONA (ID_PERSONA);

-- FACTURA_PAGO CON RELACION A FORMA_DE_PAGO
ALTER TABLE FACTURA_PAGO ADD CONSTRAINT FK_FORMA_DE_PAGO_FACTURA_PAGO FOREIGN KEY FK_FORMA_DE_PAGO_FACTURA_PAGO (ID_FPAGO)
 REFERENCES forma_De_pago(ID_FPAGO);
 -- FACTURA_PAGO CON RELACION A FACTURA
ALTER TABLE FACTURA_PAGO ADD CONSTRAINT FK_FACTURA_FACTURA_PAGO FOREIGN KEY FK_FACTURA_FACTURA_PAGO (ID_FACTURA)
    REFERENCES FACTURA (ID_FACTURA);
    
-- FACTURA DETALLE RELACION CON PRODUCTO Y FACTURA
ALTER TABLE FACTURA_DETALLE ADD CONSTRAINT FK_PRODUCTO_FACTURA_DETALLE FOREIGN KEY FK_PRODUCTO_FACTURA_DETALLE (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE FACTURA_DETALLE ADD CONSTRAINT FK_FACTURA_FACTURA_DETALLE FOREIGN KEY FK_FACTURA_FACTURA_DETALLE (ID_FACTURA)
    REFERENCES FACTURA (ID_FACTURA); 