-- FUNCIONES

-- 1) CANTIDAD DE PERSONAS CON EL ROL DADO POR PARAMETRO

DROP FUNCTION IF EXISTS cant_personas_segun_rol;

DELIMITER //
CREATE FUNCTION cant_personas_segun_rol (rol INT) RETURNS INT
    COMMENT 'Esta funcion retorna la cantidad de personas que tienen asignado el rol dado.'
	DETERMINISTIC
    BEGIN
		DECLARE CANTIDAD INT;
        SELECT COUNT(1) INTO CANTIDAD FROM PERSONA WHERE ID_ROL = rol;
        RETURN CANTIDAD;
    END//
    
DELIMITER ;

SELECT cant_personas_segun_rol(1) FROM DUAL;


-- 2) DADO UN ID PRODUCTO, INDICAR SI TIENE STOCK
DROP FUNCTION IF EXISTS tieneStock;

DELIMITER //
CREATE FUNCTION tieneStock (ID INT) RETURNS BOOLEAN
    COMMENT 'Esta funcion indica si el producto dado por parámetro tiene stock'
	DETERMINISTIC
    BEGIN
		DECLARE STOCK NUMERIC(5,0);
        SELECT CANTIDAD INTO STOCK FROM PRODUCTO_STOCK WHERE ID_PRODUCTO = ID;
        RETURN STOCK > 0;
    END//
    
DELIMITER ;

SELECT tieneStock(3) FROM DUAL;

-- 3) CANTIDAD DE FACTURAS EMITIDAS POR EL EMPLEADO DADO POR PARAMETRO
DROP FUNCTION IF EXISTS facturasDelEmpleado;

DELIMITER //
CREATE FUNCTION facturasDelEmpleado (ID INT) RETURNS INT
    COMMENT 'Esta funcion indica si la cantidad de facturas que realizó el empleado dado'
	DETERMINISTIC
    BEGIN
		DECLARE CANTIDAD INT;
        SELECT COUNT(1) INTO CANTIDAD FROM FACTURA WHERE COD_EMPLEADO = ID;
        RETURN CANTIDAD;
    END//
    
DELIMITER ;

SELECT facturasDelEmpleado(3) FROM DUAL;

-- 4) NOMBRE COMPLETO DE LA PERSONA DADA POR PARAMETRO
DROP FUNCTION IF EXISTS nombreCompleto;

DELIMITER //
CREATE FUNCTION nombreCompleto (ID INT) RETURNS VARCHAR(61)
    COMMENT 'Esta función retorna el nombre completo de la persona dada por parámetro.'
	NO SQL
BEGIN
    DECLARE NOMBRE_PERSONA VARCHAR(30);
    DECLARE APELLIDO_PERSONA VARCHAR(30);
    DECLARE NOMBRE_COMPLETO VARCHAR(61);
    
    SELECT NOMBRE, APELLIDO
    INTO NOMBRE_PERSONA, APELLIDO_PERSONA
    FROM
		PERSONA
    WHERE
		ID_PERSONA = ID;
    
    SET NOMBRE_COMPLETO = CONCAT(NOMBRE_PERSONA, ' ', APELLIDO_PERSONA);
    
    RETURN NOMBRE_COMPLETO;
END//
    
DELIMITER ;

SELECT nombreCompleto(1) FROM DUAL;


-- 5) PRODUCTO ESTRELLA, MAS VENDIDO DEL NEGOCIO.

DROP FUNCTION IF EXISTS productoEstrella;

DELIMITER //
CREATE FUNCTION productoEstrella () RETURNS INT
    COMMENT 'Esta funcion retorna el id del producto mas vendido'
	DETERMINISTIC
    BEGIN
		DECLARE ID_PROD INT;
        SELECT ID_PRODUCTO INTO ID_PROD
		FROM
			(SELECT 
				ID_PRODUCTO,
                COUNT(ID_PRODUCTO) AS CANTIDAD_VENDIDA
				FROM
					FACTURA_DETALLE
				GROUP BY 
					ID_PRODUCTO
				ORDER BY CANTIDAD_VENDIDA DESC
				LIMIT 1
			) AS producto_Mas_Vendido;
			
        RETURN ID_PROD;
    END//
    
DELIMITER ;

SELECT productoEstrella() FROM DUAL;
